const $=id=>document.getElementById(id);let papers=[],report=null,searchPapers=[];
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const say=x=>$('status').textContent=x;
async function api(path,data){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error);return result;}
function invalidate(){report=null;$('exportMd').disabled=$('exportJson').disabled=true;$('output').innerHTML='<p>Reading list changed. Run analysis to generate the current report.</p>';}
function library(){ $('library').innerHTML=papers.map((p,i)=>`<div class="library-item"><div><b>P${i+1} · ${esc(p.title)}</b><p>${esc(p.source_type||'Imported text')} · ${p.text.length.toLocaleString()} characters</p></div><button class="secondary" data-remove="${i}" aria-label="Remove paper ${i+1}">×</button></div>`).join('');}
$('library').onclick=e=>{if(e.target.dataset.remove!==undefined){papers.splice(Number(e.target.dataset.remove),1);invalidate();library();}};
function addPaper(p){if(papers.length>=10)throw Error('Maximum 10 papers.');if(!p.title.trim()||p.text.trim().length<80)throw Error('Add a title and at least 80 characters of text.');papers.push(p);invalidate();library();}
$('add').onclick=()=>{try{addPaper({title:$('title').value,authors:$('authors').value,year:$('year').value,doi:$('doi').value,text:$('text').value,source_type:'User-supplied text'});['title','authors','year','doi','text'].forEach(k=>$(k).value='');say('Paper added.');}catch(e){say(e.message);}};
$('demo').onclick=async()=>{try{papers=await(await fetch('/sample')).json();invalidate();library();say('Two fictional example papers loaded.');}catch(e){say(e.message);}};
$('jsonFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const data=JSON.parse(await f.text());if(!Array.isArray(data)||data.length>10||data.some(p=>typeof p.title!=='string'||typeof p.text!=='string'))throw Error('JSON must be an array of up to ten papers with title and text.');papers=data;invalidate();library();say('Reading list imported.');}catch(e){say(e.message);}};
$('paperFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>8000000)throw Error('File must be under 8 MB.');if(f.name.toLowerCase().endsWith('.pdf')){say('Extracting PDF text…');const bytes=new Uint8Array(await f.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const data=await api('/api/pdf',{content:btoa(binary)});$('text').value=data.text;say(data.truncated?'Text truncated to 250,000 characters. Review before adding.':'Text extracted. Review title and text before adding.');}else{$('text').value=await f.text();say('Text loaded. Review before adding.');}if(!$('title').value)$('title').value=f.name.replace(/\.(pdf|txt)$/i,'');}catch(e){say(e.message);}};
$('search').onclick=async()=>{ $('search').disabled=true;say('Searching Crossref metadata…');try{const data=await api('/api/search',{query:$('query').value});searchPapers=data.papers;$('searchResults').innerHTML=data.papers.map((p,i)=>`<div class="search-item"><b>${esc(p.title)}</b><small>${esc(p.year)} · ${esc(p.authors)}</small><p>${p.text?'Abstract available':'No abstract — full text needed'}</p>${p.doi?`<a href="https://doi.org/${encodeURIComponent(p.doi)}" target="_blank" rel="noopener noreferrer">Publisher / DOI ↗</a>`:''}<br><button class="secondary" data-select="${i}">Use in editor</button></div>`).join('')||'<p>No records found.</p>';say('Search finished. Select a record and verify its text.');}catch(e){say(e.message);}finally{$('search').disabled=false;}};
$('searchResults').onclick=e=>{if(e.target.dataset.select!==undefined){const p=searchPapers[Number(e.target.dataset.select)];['title','authors','year','doi','text'].forEach(k=>$(k).value=p[k]);say('Record loaded in editor. Add full text if abstract is missing.');}};
const quotes=(items,id)=>items.length?items.map(q=>`<blockquote><small>[${esc(id)}, sentence ${q.sentence}] Source excerpt</small>${esc(q.quote)}</blockquote>`).join(''):'<p>Not detected in supplied text.</p>';
function render(d){$('output').innerHTML=`<div class="trace">${d.trace.map(t=>`<span>${esc(t)}</span>`).join('')}</div><p>${esc(d.review.overview)}</p>${d.papers.map(p=>`<article class="paper-report"><h3>[${esc(p.id)}] ${esc(p.title)}</h3><p>${esc(p.authors)} · ${esc(p.year)} · ${esc(p.source_type)} · ${p.sentence_count} sentences</p><div>${p.keywords.map(k=>`<span class="tag">${esc(k)}</span>`).join('')}</div><h4>Extractive summary</h4>${quotes(p.summary,p.id)}<details><summary>Methodology, data, results & limitations</summary>${Object.entries(p.evidence).map(([k,v])=>`<h4>${esc(k)}</h4>${quotes(v,p.id)}`).join('')}</details><details open><summary>Critical screening</summary>${p.critique.checklist.map(c=>`<div class="check"><b>${esc(c.criterion)}</b><small>${esc(c.status)}</small>${c.evidence.length?quotes(c.evidence,p.id):''}</div>`).join('')}<p>${esc(p.critique.scope)}</p></details></article>`).join('')}<h3>Cross-paper evidence matrix</h3><div class="table-wrap"><table><thead><tr><th>Paper</th><th>Method</th><th>Data</th><th>Results</th></tr></thead><tbody>${d.comparison.rows.map(r=>`<tr><td>${esc(r.id)} · ${esc(r.title)}</td>${['method','data','results'].map(k=>`<td>${r[k].length?esc(r[k][0].quote):'Not detected'}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>${esc(d.comparison.caution)}</p><h3>Questions for further review</h3><ul>${d.review.research_gaps_to_verify.map(q=>`<li>${esc(q)}</li>`).join('')||'<li>All configured signals were mentioned. Verify adequacy against full papers.</li>'}</ul><p>${esc(d.review.limitations)}</p>`;}
$('analyze').onclick=async()=>{$('analyze').disabled=true;invalidate();say('Agents are reviewing the papers…');try{report=await api('/api/analyze',{papers});render(report);$('exportMd').disabled=$('exportJson').disabled=false;say('Review complete.');}catch(e){say(e.message);}finally{$('analyze').disabled=false;}};
function download(content,name,mime){const url=URL.createObjectURL(new Blob([content],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('exportMd').onclick=()=>report&&download(report.markdown,'chetan-research-review.md','text/markdown');$('exportJson').onclick=()=>report&&download(JSON.stringify(report,null,2),'chetan-research-review.json','application/json');
